#pragma once

#include "heap.h"
#include "visitor.h"

namespace python {

class Runtime;

// List of predefined symbols, one per line
#define FOREACH_SYMBOL(V)                                                      \
  V(DunderAbs, "__abs__")                                                      \
  V(DunderAbstractMethods, "__abstractmethods__")                              \
  V(DunderAdd, "__add__")                                                      \
  V(DunderAenter, "__aenter__")                                                \
  V(DunderAexit, "__aexit__")                                                  \
  V(DunderAiter, "__aiter__")                                                  \
  V(DunderAnd, "__and__")                                                      \
  V(DunderAnext, "__anext__")                                                  \
  V(DunderAnnotations, "__annotations__")                                      \
  V(DunderAwait, "__await__")                                                  \
  V(DunderBases, "__bases__")                                                  \
  V(DunderBool, "__bool__")                                                    \
  V(DunderBuildClass, "__build_class__")                                       \
  V(DunderBuiltins, "__builtins__")                                            \
  V(DunderBytes, "__bytes__")                                                  \
  V(DunderCall, "__call__")                                                    \
  V(DunderCause, "__cause__")                                                  \
  V(DunderCeil, "__ceil__")                                                    \
  V(DunderClass, "__class__")                                                  \
  V(DunderClassCell, "__classcell__")                                          \
  V(DunderCode, "__code__")                                                    \
  V(DunderComplex, "__complex__")                                              \
  V(DunderContains, "__contains__")                                            \
  V(DunderContext, "__context__")                                              \
  V(DunderDebug, "__debug__")                                                  \
  V(DunderDel, "__del__")                                                      \
  V(DunderDelattr, "__delattr__")                                              \
  V(DunderDelete, "__delete__")                                                \
  V(DunderDelitem, "__delitem__")                                              \
  V(DunderDict, "__dict__")                                                    \
  V(DunderDir, "__dir__")                                                      \
  V(DunderDivmod, "__divmod__")                                                \
  V(DunderDoc, "__doc__")                                                      \
  V(DunderEnter, "__enter__")                                                  \
  V(DunderEq, "__eq__")                                                        \
  V(DunderExit, "__exit__")                                                    \
  V(DunderFile, "__file__")                                                    \
  V(DunderFlags, "__flags__")                                                  \
  V(DunderFloat, "__float__")                                                  \
  V(DunderFloor, "__floor__")                                                  \
  V(DunderFloordiv, "__floordiv__")                                            \
  V(DunderFormat, "__format__")                                                \
  V(DunderFspath, "__fspath__")                                                \
  V(DunderFunc, "__func__")                                                    \
  V(DunderGe, "__ge__")                                                        \
  V(DunderGet, "__get__")                                                      \
  V(DunderGetattr, "__getattr__")                                              \
  V(DunderGetattribute, "__getattribute__")                                    \
  V(DunderGetitem, "__getitem__")                                              \
  V(DunderGlobals, "__globals__")                                              \
  V(DunderGt, "__gt__")                                                        \
  V(DunderHash, "__hash__")                                                    \
  V(DunderIadd, "__iadd__")                                                    \
  V(DunderIand, "__iand__")                                                    \
  V(DunderIfloordiv, "__ifloordiv__")                                          \
  V(DunderIlshift, "__ilshift__")                                              \
  V(DunderImatmul, "__imatmul__")                                              \
  V(DunderImod, "__imod__")                                                    \
  V(DunderImport, "__import__")                                                \
  V(DunderImul, "__imul__")                                                    \
  V(DunderIndex, "__index__")                                                  \
  V(DunderInit, "__init__")                                                    \
  V(DunderInt, "__int__")                                                      \
  V(DunderInvert, "__invert__")                                                \
  V(DunderIor, "__ior__")                                                      \
  V(DunderIpow, "__ipow__")                                                    \
  V(DunderIrshift, "__irshift__")                                              \
  V(DunderIsAbstractMethod, "__isabstractmethod__")                            \
  V(DunderIsub, "__isub__")                                                    \
  V(DunderIter, "__iter__")                                                    \
  V(DunderItruediv, "__itruediv__")                                            \
  V(DunderIxor, "__ixor__")                                                    \
  V(DunderKeys, "__keys__")                                                    \
  V(DunderLe, "__le__")                                                        \
  V(DunderLen, "__len__")                                                      \
  V(DunderLengthHint, "__length_hint__")                                       \
  V(DunderLoader, "__loader__")                                                \
  V(DunderLshift, "__lshift__")                                                \
  V(DunderLt, "__lt__")                                                        \
  V(DunderMain, "__main__")                                                    \
  V(DunderMatmul, "__matmul__")                                                \
  V(DunderMod, "__mod__")                                                      \
  V(DunderModule, "__module__")                                                \
  V(DunderMro, "__mro__")                                                      \
  V(DunderMul, "__mul__")                                                      \
  V(DunderName, "__name__")                                                    \
  V(DunderNe, "__ne__")                                                        \
  V(DunderNeg, "__neg__")                                                      \
  V(DunderNew, "__new__")                                                      \
  V(DunderNext, "__next__")                                                    \
  V(DunderOr, "__or__")                                                        \
  V(DunderPackage, "__package__")                                              \
  V(DunderPos, "__pos__")                                                      \
  V(DunderPow, "__pow__")                                                      \
  V(DunderPrepare, "__prepare__")                                              \
  V(DunderQualname, "__qualname__")                                            \
  V(DunderRadd, "__radd__")                                                    \
  V(DunderRand, "__rand__")                                                    \
  V(DunderRdivmod, "__rdivmod__")                                              \
  V(DunderRepr, "__repr__")                                                    \
  V(DunderRfloordiv, "__rfloordiv__")                                          \
  V(DunderRlshift, "__rlshift__")                                              \
  V(DunderRmatmul, "__rmatmul__")                                              \
  V(DunderRmod, "__rmod__")                                                    \
  V(DunderRmul, "__rmul__")                                                    \
  V(DunderRor, "__ror__")                                                      \
  V(DunderRound, "__round__")                                                  \
  V(DunderRpow, "__rpow__")                                                    \
  V(DunderRrshift, "__rrshift__")                                              \
  V(DunderRshift, "__rshift__")                                                \
  V(DunderRsub, "__rsub__")                                                    \
  V(DunderRtruediv, "__rtruediv__")                                            \
  V(DunderRxor, "__rxor__")                                                    \
  V(DunderSelf, "__self__")                                                    \
  V(DunderSet, "__set__")                                                      \
  V(DunderSetattr, "__setattr__")                                              \
  V(DunderSetitem, "__setitem__")                                              \
  V(DunderSizeof, "__sizeof__")                                                \
  V(DunderSpec, "__spec__")                                                    \
  V(DunderStr, "__str__")                                                      \
  V(DunderSub, "__sub__")                                                      \
  V(DunderSubclasses, "__subclasses__")                                        \
  V(DunderSuppressContext, "__suppress_context__")                             \
  V(DunderTraceback, "__traceback__")                                          \
  V(DunderTruediv, "__truediv__")                                              \
  V(DunderTrunc, "__trunc__")                                                  \
  V(DunderValues, "__values__")                                                \
  V(DunderXor, "__xor__")                                                      \
  V(UnderAddress, "_address")                                                  \
  V(UnderAsciiDecode, "_ascii_decode")                                         \
  V(UnderAsciiEncode, "_ascii_encode")                                         \
  V(UnderBaseDir, "_base_dir")                                                 \
  V(UnderBases, "_bases")                                                      \
  V(UnderBootstrap, "_bootstrap")                                              \
  V(UnderBoundMethod, "_bound_method")                                         \
  V(UnderBuffer, "_buffer")                                                    \
  V(UnderBufferedIOBase, "_BufferedIOBase")                                    \
  V(UnderBuiltins, "_builtins")                                                \
  V(UnderByteArrayCheck, "_bytearray_check")                                   \
  V(UnderByteArrayClear, "_bytearray_clear")                                   \
  V(UnderByteArrayGuard, "_bytearray_guard")                                   \
  V(UnderByteArrayJoin, "_bytearray_join")                                     \
  V(UnderByteArrayLen, "_bytearray_len")                                       \
  V(UnderByteArraySetitem, "_bytearray_setitem")                               \
  V(UnderByteArraySetslice, "_bytearray_setslice")                             \
  V(UnderByteArrayStringAppend, "_bytearray_string_append")                    \
  V(UnderBytesCheck, "_bytes_check")                                           \
  V(UnderBytesFromInts, "_bytes_from_ints")                                    \
  V(UnderBytesGetitem, "_bytes_getitem")                                       \
  V(UnderBytesGetslice, "_bytes_getslice")                                     \
  V(UnderBytesGuard, "_bytes_guard")                                           \
  V(UnderBytesJoin, "_bytes_join")                                             \
  V(UnderBytesLen, "_bytes_len")                                               \
  V(UnderBytesMaketrans, "_bytes_maketrans")                                   \
  V(UnderBytesNew, "_bytes_new")                                               \
  V(UnderBytesRepeat, "_bytes_repeat")                                         \
  V(UnderBytesSplit, "_bytes_split")                                           \
  V(UnderBytesSplitWhitespace, "_bytes_split_whitespace")                      \
  V(UnderByteslikeCount, "_byteslike_count")                                   \
  V(UnderByteslikeEndsWith, "_byteslike_endswith")                             \
  V(UnderByteslikeFindByteslike, "_byteslike_find_byteslike")                  \
  V(UnderByteslikeFindInt, "_byteslike_find_int")                              \
  V(UnderByteslikeRfindByteslike, "_byteslike_rfind_byteslike")                \
  V(UnderByteslikeRfindInt, "_byteslike_rfind_int")                            \
  V(UnderClassMethod, "_classmethod")                                          \
  V(UnderClassMethodIsAbstract, "_classmethod_isabstract")                     \
  V(UnderClosed, "_closed")                                                    \
  V(UnderCodecs, "_codecs")                                                    \
  V(UnderCodeGuard, "_code_guard")                                             \
  V(UnderComplexImag, "_complex_imag")                                         \
  V(UnderComplexReal, "_complex_real")                                         \
  V(UnderDelattr, "_delattr")                                                  \
  V(UnderDescrClassMethod, "_descrclassmethod")                                \
  V(UnderDictBucketInsert, "_dict_bucket_insert")                              \
  V(UnderDictBucketKey, "_dict_bucket_key")                                    \
  V(UnderDictBucketUpdate, "_dict_bucket_update")                              \
  V(UnderDictBucketValue, "_dict_bucket_value")                                \
  V(UnderDictCheck, "_dict_check")                                             \
  V(UnderDictGetItem, "_dict_getitem")                                         \
  V(UnderDictGuard, "_dict_guard")                                             \
  V(UnderDictLen, "_dict_len")                                                 \
  V(UnderDictLookup, "_dict_lookup")                                           \
  V(UnderDictLookupNext, "_dict_lookup_next")                                  \
  V(UnderDictPopitem, "_dict_popitem")                                         \
  V(UnderDictSetItem, "_dict_setitem")                                         \
  V(UnderDictUpdateMapping, "_dict_update_mapping")                            \
  V(UnderDivmod, "_divmod")                                                    \
  V(UnderEscapeDecode, "_escape_decode")                                       \
  V(UnderEscapeDecodeStateful, "_escape_decode_stateful")                      \
  V(UnderExceptionNew, "_exception_new")                                       \
  V(UnderFindAndLoad, "_find_and_load")                                        \
  V(UnderFloatCheck, "_float_check")                                           \
  V(UnderFloatDivmod, "_float_divmod")                                         \
  V(UnderFloatFormat, "_float_format")                                         \
  V(UnderFloatGuard, "_float_guard")                                           \
  V(UnderFloatSignbit, "_float_signbit")                                       \
  V(UnderFrozenImportlib, "_frozen_importlib")                                 \
  V(UnderFrozenImportlibExternal, "_frozen_importlib_external")                \
  V(UnderFrozenSetCheck, "_frozenset_check")                                   \
  V(UnderFrozenSetGuard, "_frozenset_guard")                                   \
  V(UnderFunctools, "_functools")                                              \
  V(UnderGetframeCode, "_getframe_code")                                       \
  V(UnderGetframeGlobals, "_getframe_globals")                                 \
  V(UnderGetframeLineno, "_getframe_lineno")                                   \
  V(UnderGetMemberByte, "_get_member_byte")                                    \
  V(UnderGetMemberChar, "_get_member_char")                                    \
  V(UnderGetMemberDouble, "_get_member_double")                                \
  V(UnderGetMemberFloat, "_get_member_float")                                  \
  V(UnderGetMemberInt, "_get_member_int")                                      \
  V(UnderGetMemberLong, "_get_member_long")                                    \
  V(UnderGetMemberPyObject, "_get_member_pyobject")                            \
  V(UnderGetMemberShort, "_get_member_short")                                  \
  V(UnderGetMemberString, "_get_member_string")                                \
  V(UnderGetMemberUByte, "_get_member_ubyte")                                  \
  V(UnderGetMemberUInt, "_get_member_uint")                                    \
  V(UnderGetMemberULong, "_get_member_ulong")                                  \
  V(UnderGetMemberUShort, "_get_member_ushort")                                \
  V(UnderImp, "_imp")                                                          \
  V(UnderIndex, "_index")                                                      \
  V(UnderInstall, "_install")                                                  \
  V(UnderInstanceGetattr, "_instance_getattr")                                 \
  V(UnderInstanceSetattr, "_instance_setattr")                                 \
  V(UnderIntCheck, "_int_check")                                               \
  V(UnderIntCheckExact, "_int_checkexact")                                     \
  V(UnderIntFromBytes, "_int_from_bytes")                                      \
  V(UnderIntGuard, "_int_guard")                                               \
  V(UnderIntNewFromByteArray, "_int_new_from_bytearray")                       \
  V(UnderIntNewFromBytes, "_int_new_from_bytes")                               \
  V(UnderIntNewFromInt, "_int_new_from_int")                                   \
  V(UnderIntNewFromStr, "_int_new_from_str")                                   \
  V(UnderIOBase, "_IOBase")                                                    \
  V(UnderIo, "_io")                                                            \
  V(UnderLatin1Decode, "_latin_1_decode")                                      \
  V(UnderLatin1Encode, "_latin_1_encode")                                      \
  V(UnderListCheck, "_list_check")                                             \
  V(UnderListCheckExact, "_list_checkexact")                                   \
  V(UnderListDelitem, "_list_delitem")                                         \
  V(UnderListDelslice, "_list_delslice")                                       \
  V(UnderListExtend, "_list_extend")                                           \
  V(UnderListGetitem, "_list_getitem")                                         \
  V(UnderListGetslice, "_list_getslice")                                       \
  V(UnderListGuard, "_list_guard")                                             \
  V(UnderListLen, "_list_len")                                                 \
  V(UnderListSort, "_list_sort")                                               \
  V(UnderListSwap, "_list_swap")                                               \
  V(UnderLookupText, "_lookup_text")                                           \
  V(UnderMemoryviewGuard, "_memoryview_guard")                                 \
  V(UnderMemoryviewNbytes, "_memoryview_nbytes")                               \
  V(UnderModuleDir, "_module_dir")                                             \
  V(UnderModuleRepr, "_module_repr")                                           \
  V(UnderModuleProxy, "_module_proxy")                                         \
  V(UnderModuleProxyDelitem, "_module_proxy_delitem")                          \
  V(UnderModuleProxyGet, "_module_proxy_get")                                  \
  V(UnderModuleProxyGuard, "_module_proxy_guard")                              \
  V(UnderModuleProxyKeys, "_module_proxy_keys")                                \
  V(UnderModuleProxyLen, "_module_proxy_len")                                  \
  V(UnderModuleProxySetitem, "_module_proxy_setitem")                          \
  V(UnderModuleProxyValues, "_module_proxy_values")                            \
  V(UnderMutableBytes, "_mutablebytes")                                        \
  V(UnderNewMemberGetBool, "_new_member_get_bool")                             \
  V(UnderNewMemberGetByte, "_new_member_get_byte")                             \
  V(UnderNewMemberGetChar, "_new_member_get_char")                             \
  V(UnderNewMemberGetDouble, "_new_member_get_double")                         \
  V(UnderNewMemberGetFloat, "_new_member_get_float")                           \
  V(UnderNewMemberGetInt, "_new_member_get_int")                               \
  V(UnderNewMemberGetLong, "_new_member_get_long")                             \
  V(UnderNewMemberGetNone, "_new_member_get_none")                             \
  V(UnderNewMemberGetPyObject, "_new_member_get_pyobject")                     \
  V(UnderNewMemberGetShort, "_new_member_get_short")                           \
  V(UnderNewMemberGetString, "_new_member_get_string")                         \
  V(UnderNewMemberGetUByte, "_new_member_get_ubyte")                           \
  V(UnderNewMemberGetUInt, "_new_member_get_uint")                             \
  V(UnderNewMemberGetUIntegral, "_new_member_get_uintegral")                   \
  V(UnderNewMemberGetULong, "_new_member_get_ulong")                           \
  V(UnderNewMemberGetUShort, "_new_member_get_ushort")                         \
  V(UnderNewMemberSetBool, "_new_member_set_bool")                             \
  V(UnderNewMemberSetChar, "_new_member_set_char")                             \
  V(UnderNewMemberSetDouble, "_new_member_set_double")                         \
  V(UnderNewMemberSetFloat, "_new_member_set_float")                           \
  V(UnderNewMemberSetIntegral, "_new_member_set_integral")                     \
  V(UnderNewMemberSetPyObject, "_new_member_set_pyobject")                     \
  V(UnderNewMemberSetReadonly, "_new_member_set_readonly")                     \
  V(UnderNewMemberSetReadonlyStrings, "_new_member_set_readonly_strings")      \
  V(UnderNumberCheck, "_number_check")                                         \
  V(UnderObjectTypeGetattr, "_object_type_getattr")                            \
  V(UnderObjectTypeHasattr, "_object_type_hasattr")                            \
  V(UnderOsClose, "_os_close")                                                 \
  V(UnderOsRead, "_os_read")                                                   \
  V(UnderOsWrite, "_os_write")                                                 \
  V(UnderPatch, "_patch")                                                      \
  V(UnderPos, "_pos")                                                          \
  V(UnderProperty, "_property")                                                \
  V(UnderPropertyIsAbstract, "_property_isabstract")                           \
  V(UnderPyObjectOffset, "_pyobject_offset")                                   \
  V(UnderRangeCheck, "_range_check")                                           \
  V(UnderRangeGuard, "_range_guard")                                           \
  V(UnderRangeLen, "_range_len")                                               \
  V(UnderRawIOBase, "_RawIOBase")                                              \
  V(UnderReadBytes, "_readbytes")                                              \
  V(UnderReadFile, "_readfile")                                                \
  V(UnderReferent, "_referent")                                                \
  V(UnderReprEnter, "_repr_enter")                                             \
  V(UnderReprLeave, "_repr_leave")                                             \
  V(UnderSeqIndex, "_seq_index")                                               \
  V(UnderSeqIterable, "_seq_iterable")                                         \
  V(UnderSeqSetIndex, "_seq_set_index")                                        \
  V(UnderSeqSetIterable, "_seq_set_iterable")                                  \
  V(UnderSetCheck, "_set_check")                                               \
  V(UnderSetGuard, "_set_guard")                                               \
  V(UnderSetLen, "_set_len")                                                   \
  V(UnderSetMemberDouble, "_set_member_double")                                \
  V(UnderSetMemberFloat, "_set_member_float")                                  \
  V(UnderSetMemberIntegral, "_set_member_integral")                            \
  V(UnderSetMemberPyObject, "_set_member_pyobject")                            \
  V(UnderSliceCheck, "_slice_check")                                           \
  V(UnderSliceGuard, "_slice_guard")                                           \
  V(UnderSliceIndex, "_slice_index")                                           \
  V(UnderSliceIndexNotNone, "_slice_index_not_none")                           \
  V(UnderSliceStart, "_slice_start")                                           \
  V(UnderSliceStep, "_slice_step")                                             \
  V(UnderSliceStop, "_slice_stop")                                             \
  V(UnderStaticMethodIsAbstract, "_staticmethod_isabstract")                   \
  V(UnderStderrFd, "_stderr_fd")                                               \
  V(UnderStdout, "_stdout")                                                    \
  V(UnderStdoutFd, "_stdout_fd")                                               \
  V(UnderStrArray, "_strarray")                                                \
  V(UnderStrArrayIadd, "_strarray_iadd")                                       \
  V(UnderStrCheck, "_str_check")                                               \
  V(UnderStrCheckExact, "_str_checkexact")                                     \
  V(UnderStrCount, "_str_count")                                               \
  V(UnderStrGuard, "_str_guard")                                               \
  V(UnderStrJoin, "_str_join")                                                 \
  V(UnderStrEscapeNonAscii, "_str_escape_non_ascii")                           \
  V(UnderStrFind, "_str_find")                                                 \
  V(UnderStrFromStr, "_str_from_str")                                          \
  V(UnderStrLen, "_str_len")                                                   \
  V(UnderStrMod, "_str_mod")                                                   \
  V(UnderStrReplace, "_str_replace")                                           \
  V(UnderStrRFind, "_str_rfind")                                               \
  V(UnderStrSplitlines, "_str_splitlines")                                     \
  V(UnderStructseqField, "_structseq_field")                                   \
  V(UnderStructseqFieldNames, "_structseq_field_names")                        \
  V(UnderStructseqGetItem, "_structseq_getitem")                               \
  V(UnderStructseqNew, "_structseq_new")                                       \
  V(UnderStructseqRepr, "_structseq_repr")                                     \
  V(UnderThread, "_thread")                                                    \
  V(UnderTupleCheck, "_tuple_check")                                           \
  V(UnderTupleCheckExact, "_tuple_checkexact")                                 \
  V(UnderTupleGuard, "_tuple_guard")                                           \
  V(UnderTupleLen, "_tuple_len")                                               \
  V(UnderTupleNew, "_tuple_new")                                               \
  V(UnderTraceback, "_traceback")                                              \
  V(UnderType, "_type")                                                        \
  V(UnderTypeAbstractMethodsDel, "_type_abstractmethods_del")                  \
  V(UnderTypeAbstractMethodsGet, "_type_abstractmethods_get")                  \
  V(UnderTypeAbstractMethodsSet, "_type_abstractmethods_set")                  \
  V(UnderTypeBasesDel, "_type_bases_del")                                      \
  V(UnderTypeBasesGet, "_type_bases_get")                                      \
  V(UnderTypeBasesSet, "_type_bases_set")                                      \
  V(UnderTypeCheck, "_type_check")                                             \
  V(UnderTypeCheckExact, "_type_check_exact")                                  \
  V(UnderTypeDictKeys, "_type_dict_keys")                                      \
  V(UnderTypeGuard, "_type_guard")                                             \
  V(UnderTypeIsSubclass, "_type_issubclass")                                   \
  V(UnderUnbound, "_Unbound")                                                  \
  V(UnderUnicodeEscapeDecode, "_unicode_escape_decode")                        \
  V(UnderUnicodeEscapeDecodeStateful, "_unicode_escape_decode_stateful")       \
  V(UnderUnimplemented, "_unimplemented")                                      \
  V(UnderUtf16Encode, "_utf_16_encode")                                        \
  V(UnderUtf32Encode, "_utf_32_encode")                                        \
  V(UnderUtf8Decode, "_utf_8_decode")                                          \
  V(UnderUtf8DecodeStateful, "_utf_8_decode_stateful")                         \
  V(UnderUtf8Encode, "_utf_8_encode")                                          \
  V(UnderWarnings, "_warnings")                                                \
  V(UnderWeakLink, "_weaklink")                                                \
  V(UnderWeakRef, "_weakref")                                                  \
  V(Abs, "abs")                                                                \
  V(AcquireLock, "acquire_lock")                                               \
  V(Add, "add")                                                                \
  V(AndUnder, "and_")                                                          \
  V(Anonymous, "<anonymous>")                                                  \
  V(Append, "append")                                                          \
  V(Args, "args")                                                              \
  V(Argv, "argv")                                                              \
  V(ArithmeticError, "ArithmeticError")                                        \
  V(Ascii, "ascii")                                                            \
  V(AsciiDecode, "ascii_decode")                                               \
  V(AsciiEncode, "ascii_encode")                                               \
  V(AssertionError, "AssertionError")                                          \
  V(AsyncGenerator, "async_generator")                                         \
  V(AttributeError, "AttributeError")                                          \
  V(Backslashreplace, "backslashreplace")                                      \
  V(BadArgumentToInternalFunction, "bad argument to internal function")        \
  V(BadArgumentTypeForBuiltinOperation,                                        \
    "bad argument type for built-in operation")                                \
  V(BaseException, "BaseException")                                            \
  V(Big, "big")                                                                \
  V(Bin, "bin")                                                                \
  V(BitLength, "bit_length")                                                   \
  V(BlockingIOError, "BlockingIOError")                                        \
  V(Bool, "bool")                                                              \
  V(Bootstrap, "bootstrap")                                                    \
  V(BrokenPipeError, "BrokenPipeError")                                        \
  V(BufferError, "BufferError")                                                \
  V(BuiltinModuleNames, "builtin_module_names")                                \
  V(Builtins, "builtins")                                                      \
  V(ByteArray, "bytearray")                                                    \
  V(ByteArrayIterator, "bytearray_iterator")                                   \
  V(Byteorder, "byteorder")                                                    \
  V(Bytes, "bytes")                                                            \
  V(BytesIO, "BytesIO")                                                        \
  V(BytesIterator, "bytes_iterator")                                           \
  V(BytesWarning, "BytesWarning")                                              \
  V(Callable, "callable")                                                      \
  V(Cast, "cast")                                                              \
  V(Cause, "cause")                                                            \
  V(ChildProcessError, "ChildProcessError")                                    \
  V(Chr, "chr")                                                                \
  V(Classmethod, "classmethod")                                                \
  V(Clear, "clear")                                                            \
  V(CoArgcount, "co_argcount")                                                 \
  V(CoCellvars, "co_cellvars")                                                 \
  V(CoCode, "co_code")                                                         \
  V(CoConsts, "co_consts")                                                     \
  V(CoFilename, "co_filename")                                                 \
  V(CoFirstlineno, "co_firstlineno")                                           \
  V(CoFlags, "co_flags")                                                       \
  V(CoFreevars, "co_freevars")                                                 \
  V(CoKwonlyargcount, "co_kwonlyargcount")                                     \
  V(CoLnotab, "co_lnotab")                                                     \
  V(CoName, "co_name")                                                         \
  V(CoNames, "co_names")                                                       \
  V(CoNlocals, "co_nlocals")                                                   \
  V(CoPosonlyargcount, "co_posonlyargcount")                                   \
  V(CoStacksize, "co_stacksize")                                               \
  V(CoVarnames, "co_varnames")                                                 \
  V(Code, "code")                                                              \
  V(Compile, "compile")                                                        \
  V(Complex, "complex")                                                        \
  V(Concat, "concat")                                                          \
  V(Conjugate, "conjugate")                                                    \
  V(ConnectionAbortedError, "ConnectionAbortedError")                          \
  V(ConnectionError, "ConnectionError")                                        \
  V(ConnectionRefusedError, "ConnectionRefusedError")                          \
  V(ConnectionResetError, "ConnectionResetError")                              \
  V(Contains, "contains")                                                      \
  V(Copy, "copy")                                                              \
  V(Coroutine, "coroutine")                                                    \
  V(CountOf, "countOf")                                                        \
  V(CrRunning, "cr_running")                                                   \
  V(CreateBuiltin, "create_builtin")                                           \
  V(Deleter, "deleter")                                                        \
  V(DeprecationWarning, "DeprecationWarning")                                  \
  V(Dict, "dict")                                                              \
  V(DictItemIterator, "dict_itemiterator")                                     \
  V(DictItems, "dict_items")                                                   \
  V(DictKeyIterator, "dict_keyiterator")                                       \
  V(DictKeys, "dict_keys")                                                     \
  V(DictValueIterator, "dict_valueiterator")                                   \
  V(DictValues, "dict_values")                                                 \
  V(Discard, "discard")                                                        \
  V(Displayhook, "displayhook")                                                \
  V(Divmod, "divmod")                                                          \
  V(DotSo, ".so")                                                              \
  V(Dummy, "dummy")                                                            \
  V(EOFError, "EOFError")                                                      \
  V(Ellipsis, "ellipsis")                                                      \
  V(Encode, "encode")                                                          \
  V(Encoding, "encoding")                                                      \
  V(End, "end")                                                                \
  V(Eq, "eq")                                                                  \
  V(ExcInfo, "exc_info")                                                       \
  V(Excepthook, "excepthook")                                                  \
  V(Exception, "Exception")                                                    \
  V(ExceptionState, "ExceptionState")                                          \
  V(Exec, "exec")                                                              \
  V(ExecBuiltin, "exec_builtin")                                               \
  V(ExecDynamic, "exec_dynamic")                                               \
  V(Executable, "executable")                                                  \
  V(Exit, "exit")                                                              \
  V(Extend, "extend")                                                          \
  V(ExtensionPtr, "___extension___")                                           \
  V(ExtensionSuffixes, "extension_suffixes")                                   \
  V(False, "False")                                                            \
  V(File, "file")                                                              \
  V(FileExistsError, "FileExistsError")                                        \
  V(FileNotFoundError, "FileNotFoundError")                                    \
  V(Filename, "filename")                                                      \
  V(Fileno, "fileno")                                                          \
  V(Find, "find")                                                              \
  V(FixCoFilename, "_fix_co_filename")                                         \
  V(Float, "float")                                                            \
  V(FloatingPointError, "FloatingPointError")                                  \
  V(Floordiv, "floordiv")                                                      \
  V(Flush, "flush")                                                            \
  V(Format, "format")                                                          \
  V(Frame, "frame")                                                            \
  V(FromBytes, "from_bytes")                                                   \
  V(FrozenSet, "frozenset")                                                    \
  V(Function, "function")                                                      \
  V(FutureWarning, "FutureWarning")                                            \
  V(Generator, "generator")                                                    \
  V(GeneratorExit, "GeneratorExit")                                            \
  V(Get, "get")                                                                \
  V(GetFrozenObject, "get_frozen_object")                                      \
  V(GetSizeOf, "getsizeof")                                                    \
  V(Getattr, "getattr")                                                        \
  V(Getter, "getter")                                                          \
  V(GiRunning, "gi_running")                                                   \
  V(Globals, "globals")                                                        \
  V(Hasattr, "hasattr")                                                        \
  V(Hex, "hex")                                                                \
  V(Iadd, "iadd")                                                              \
  V(Iand, "iand")                                                              \
  V(Iconcat, "iconcat")                                                        \
  V(Id, "id")                                                                  \
  V(Ifloordiv, "ifloordiv")                                                    \
  V(Ignore, "ignore")                                                          \
  V(Ilshift, "ilshift")                                                        \
  V(Imatmul, "imatmul")                                                        \
  V(Imod, "imod")                                                              \
  V(ImportError, "ImportError")                                                \
  V(ImportWarning, "ImportWarning")                                            \
  V(Imul, "imul")                                                              \
  V(IndentationError, "IndentationError")                                      \
  V(IndexError, "IndexError")                                                  \
  V(IndexOf, "indexOf")                                                        \
  V(Insert, "insert")                                                          \
  V(Instance, "instance")                                                      \
  V(Int, "int")                                                                \
  V(InterruptedError, "InterruptedError")                                      \
  V(Intersection, "intersection")                                              \
  V(Invert, "invert")                                                          \
  V(Ior, "ior")                                                                \
  V(Ipow, "ipow")                                                              \
  V(Irepeat, "irepeat")                                                        \
  V(Irshift, "irshift")                                                        \
  V(IsADirectoryError, "IsADirectoryError")                                    \
  V(IsBuiltin, "is_builtin")                                                   \
  V(IsDisjoint, "isdisjoint")                                                  \
  V(IsFrozen, "is_frozen")                                                     \
  V(IsFrozenPackage, "is_frozen_package")                                      \
  V(IsInstance, "isinstance")                                                  \
  V(IsSubclass, "issubclass")                                                  \
  V(Isalnum, "isalnum")                                                        \
  V(Isalpha, "isalpha")                                                        \
  V(Isdecimal, "isdecimal")                                                    \
  V(Isdigit, "isdigit")                                                        \
  V(Isidentifier, "isidentifier")                                              \
  V(Islower, "islower")                                                        \
  V(Isnumeric, "isnumeric")                                                    \
  V(Isprintable, "isprintable")                                                \
  V(Isspace, "isspace")                                                        \
  V(Istitle, "istitle")                                                        \
  V(Isupper, "isupper")                                                        \
  V(Isub, "isub")                                                              \
  V(Items, "items")                                                            \
  V(Itertools, "itertools")                                                    \
  V(Itruediv, "itruediv")                                                      \
  V(Ixor, "ixor")                                                              \
  V(Join, "join")                                                              \
  V(Key, "key")                                                                \
  V(KeyError, "KeyError")                                                      \
  V(KeyboardInterrupt, "KeyboardInterrupt")                                    \
  V(Keys, "keys")                                                              \
  V(Kwargs, "kwargs")                                                          \
  V(LStrip, "lstrip")                                                          \
  V(LargeBytes, "largebytes")                                                  \
  V(LargeInt, "largeint")                                                      \
  V(LargeStr, "largestr")                                                      \
  V(LastTraceback, "last_traceback")                                           \
  V(LastType, "last_type")                                                     \
  V(LastValue, "last_value")                                                   \
  V(Latin1Decode, "latin_1_decode")                                            \
  V(Latin1Encode, "latin_1_encode")                                            \
  V(Layout, "layout")                                                          \
  V(Len, "len")                                                                \
  V(Length, "length")                                                          \
  V(Lineno, "lineno")                                                          \
  V(List, "list")                                                              \
  V(ListIterator, "list_iterator")                                             \
  V(Little, "little")                                                          \
  V(Loads, "loads")                                                            \
  V(Locals, "locals")                                                          \
  V(LongRangeIterator, "longrange_iterator")                                   \
  V(LookupError, "LookupError")                                                \
  V(Lower, "lower")                                                            \
  V(Lshift, "lshift")                                                          \
  V(Lt, "lt")                                                                  \
  V(Marshal, "marshal")                                                        \
  V(Matmul, "matmul")                                                          \
  V(Maxsize, "maxsize")                                                        \
  V(Maxunicode, "maxunicode")                                                  \
  V(MemoryError, "MemoryError")                                                \
  V(MemoryView, "memoryview")                                                  \
  V(MetaPath, "meta_path")                                                     \
  V(Metaclass, "metaclass")                                                    \
  V(Method, "method")                                                          \
  V(Mod, "mod")                                                                \
  V(Module, "module")                                                          \
  V(ModuleProxy, "module_proxy")                                               \
  V(ModuleNotFoundError, "ModuleNotFoundError")                                \
  V(Modules, "modules")                                                        \
  V(Mro, "mro")                                                                \
  V(Msg, "msg")                                                                \
  V(Mul, "mul")                                                                \
  V(NFields, "n_fields")                                                       \
  V(NSequenceFields, "n_sequence_fields")                                      \
  V(NUnnamedFields, "n_unnamed_fields")                                        \
  V(Name, "name")                                                              \
  V(NameError, "NameError")                                                    \
  V(Namedtuple, "namedtuple")                                                  \
  V(Neg, "neg")                                                                \
  V(None, "None")                                                              \
  V(NoneType, "NoneType")                                                      \
  V(NotADirectoryError, "NotADirectoryError")                                  \
  V(NotImplemented, "NotImplemented")                                          \
  V(NotImplementedError, "NotImplementedError")                                \
  V(NotImplementedType, "NotImplementedType")                                  \
  V(Null, "<NULL>")                                                            \
  V(NullArgumentToInternalRoutine, "null argument to internal routine")        \
  V(OSError, "OSError")                                                        \
  V(ObjectTypename, "object")                                                  \
  V(Oct, "oct")                                                                \
  V(Offset, "offset")                                                          \
  V(Operator, "operator")                                                      \
  V(OrUnder, "or_")                                                            \
  V(Ord, "ord")                                                                \
  V(OverflowError, "OverflowError")                                            \
  V(Owner, "owner")                                                            \
  V(Partition, "partition")                                                    \
  V(Path, "path")                                                              \
  V(PendingDeprecationWarning, "PendingDeprecationWarning")                    \
  V(PermissionError, "PermissionError")                                        \
  V(Platform, "platform")                                                      \
  V(Pop, "pop")                                                                \
  V(Pos, "pos")                                                                \
  V(Pow, "pow")                                                                \
  V(PrintFileAndLine, "print_file_and_line")                                   \
  V(ProcessLookupError, "ProcessLookupError")                                  \
  V(Property, "property")                                                      \
  V(Proxy, "proxy")                                                            \
  V(RPartition, "rpartition")                                                  \
  V(RSplit, "rsplit")                                                          \
  V(RStrip, "rstrip")                                                          \
  V(Range, "range")                                                            \
  V(RangeIterator, "range_iterator")                                           \
  V(Reason, "reason")                                                          \
  V(RecursionError, "RecursionError")                                          \
  V(Ref, "ref")                                                                \
  V(ReferenceError, "ReferenceError")                                          \
  V(ReleaseLock, "release_lock")                                               \
  V(Remove, "remove")                                                          \
  V(Replace, "replace")                                                        \
  V(Repr, "repr")                                                              \
  V(ResourceWarning, "ResourceWarning")                                        \
  V(Rfind, "rfind")                                                            \
  V(Rshift, "rshift")                                                          \
  V(RuntimeError, "RuntimeError")                                              \
  V(RuntimeWarning, "RuntimeWarning")                                          \
  V(Self, "self")                                                              \
  V(Send, "send")                                                              \
  V(SeqIterator, "iterator")                                                   \
  V(Set, "set")                                                                \
  V(SetIterator, "set_iterator")                                               \
  V(Setattr, "setattr")                                                        \
  V(Setter, "setter")                                                          \
  V(Signed, "signed")                                                          \
  V(Size, "size")                                                              \
  V(Slice, "slice")                                                            \
  V(SmallBytes, "smallbytes")                                                  \
  V(SmallInt, "smallint")                                                      \
  V(SmallStr, "smallstr")                                                      \
  V(Sorted, "sorted")                                                          \
  V(Split, "split")                                                            \
  V(Start, "start")                                                            \
  V(StaticMethod, "staticmethod")                                              \
  V(Stderr, "stderr")                                                          \
  V(Stdout, "stdout")                                                          \
  V(Step, "step")                                                              \
  V(Stop, "stop")                                                              \
  V(StopAsyncIteration, "StopAsyncIteration")                                  \
  V(StopIteration, "StopIteration")                                            \
  V(Str, "str")                                                                \
  V(StrIterator, "str_iterator")                                               \
  V(Strict, "strict")                                                          \
  V(StrictErrors, "strict_errors")                                             \
  V(Strip, "strip")                                                            \
  V(Sub, "sub")                                                                \
  V(Super, "super")                                                            \
  V(Surrogateescape, "surrogateescape")                                        \
  V(Surrogatepass, "surrogatepass")                                            \
  V(SyntaxError, "SyntaxError")                                                \
  V(SyntaxWarning, "SyntaxWarning")                                            \
  V(Sys, "sys")                                                                \
  V(SystemError, "SystemError")                                                \
  V(SystemExit, "SystemExit")                                                  \
  V(TabError, "TabError")                                                      \
  V(Text, "text")                                                              \
  V(Throw, "throw")                                                            \
  V(Time, "time")                                                              \
  V(TimeoutError, "TimeoutError")                                              \
  V(ToBytes, "to_bytes")                                                       \
  V(Traceback, "traceback")                                                    \
  V(Translate, "translate")                                                    \
  V(True, "True")                                                              \
  V(Truediv, "truediv")                                                        \
  V(Tuple, "tuple")                                                            \
  V(TupleIterator, "tuple_iterator")                                           \
  V(Type, "type")                                                              \
  V(TypeError, "TypeError")                                                    \
  V(UnboundLocalError, "UnboundLocalError")                                    \
  V(UnicodeDecodeError, "UnicodeDecodeError")                                  \
  V(UnicodeEncodeError, "UnicodeEncodeError")                                  \
  V(UnicodeError, "UnicodeError")                                              \
  V(UnicodeTranslateError, "UnicodeTranslateError")                            \
  V(UnicodeWarning, "UnicodeWarning")                                          \
  V(Update, "update")                                                          \
  V(Upper, "upper")                                                            \
  V(UserWarning, "UserWarning")                                                \
  V(Utf16Encode, "utf_16_encode")                                              \
  V(Utf32Encode, "utf_32_encode")                                              \
  V(Utf8Encode, "utf_8_encode")                                                \
  V(Value, "value")                                                            \
  V(ValueCell, "valuecell")                                                    \
  V(ValueError, "ValueError")                                                  \
  V(Values, "values")                                                          \
  V(Vars, "vars")                                                              \
  V(Version, "version")                                                        \
  V(Warn, "warn")                                                              \
  V(WarnExplicit, "warn_explicit")                                             \
  V(Warning, "Warning")                                                        \
  V(Warnings, "warnings")                                                      \
  V(Write, "write")                                                            \
  V(Xmlcharrefreplace, "xmlcharrefreplace")                                    \
  V(Xor, "xor")                                                                \
  V(ZeroDivisionError, "ZeroDivisionError")

// clang-format off
enum class SymbolId {
  kInvalid = -1,
#define DEFINE_SYMBOL_INDEX(symbol, value) k##symbol,
  FOREACH_SYMBOL(DEFINE_SYMBOL_INDEX)
#undef DEFINE_SYMBOL_INDEX
  kMaxId,
  kSentinelId,
};
// clang-format on

// Provides convenient, fast access to commonly used names. Stolen from Dart.
class Symbols {
 public:
  explicit Symbols(Runtime* runtime);
  ~Symbols();

#define DEFINE_SYMBOL_ACCESSOR(symbol, value)                                  \
  RawObject symbol() { return at(SymbolId::k##symbol); }
  FOREACH_SYMBOL(DEFINE_SYMBOL_ACCESSOR)
#undef DEFINE_SYMBOL_ACCESSOR

  void visit(PointerVisitor* visitor);

  RawObject at(SymbolId id) {
    int index = static_cast<int>(id);
    DCHECK_INDEX(index, static_cast<int>(SymbolId::kMaxId));
    return symbols_[index];
  }

  static const char* predefinedSymbolAt(SymbolId id);

 private:
  // TODO(T25010996) - Benchmark whether this is faster than an Tuple
  RawObject* symbols_;
};

}  // namespace python
