// @generated by generate_unicode_database.py
#pragma once

#include <cstdint>

namespace py {

enum : int32_t {
  kAlphaMask = 0x1,
  kDecimalMask = 0x2,
  kDigitMask = 0x4,
  kLowerMask = 0x8,
  kLinebreakMask = 0x10,
  kSpaceMask = 0x20,
  kTitleMask = 0x40,
  kUpperMask = 0x80,
  kXidStartMask = 0x100,
  kXidContinueMask = 0x200,
  kPrintableMask = 0x400,
  kNumericMask = 0x800,
  kCaseIgnorableMask = 0x1000,
  kCasedMask = 0x2000,
  kExtendedCaseMask = 0x4000,
};

struct UnicodeTypeRecord {
  // Deltas to the character or offsets in kExtendedCase
  const int32_t upper;
  const int32_t lower;
  const int32_t title;
  // Note: if more flag space is needed, decimal and digit could be unified
  const int8_t decimal;
  const int8_t digit;
  const int16_t flags;
};

const UnicodeTypeRecord* typeRecord(int32_t code_point);

}  // namespace py
