#!/usr/bin/env python3
import glob
import os
from glob import glob


SCRIPT_NAME = os.path.basename(__file__)
PYRO_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

library_files = set()
os.chdir(f"{PYRO_DIR}/library")
for filename in glob("**/*.py", recursive=True):
    library_files.add(filename)

cpython_library_files = set()
os.chdir(f"{PYRO_DIR}/third-party/cpython/Lib")
for filename in glob("**/*", recursive=True):
    if os.path.isdir(filename) or "__pycache__/" in filename:
        continue
    if filename in library_files:
        continue
    cpython_library_files.add(filename)

with open(f"{PYRO_DIR}/library_files.cmake", "w") as fp:
    fp.write(
        f"""\
# This file was generated by `util/{SCRIPT_NAME}`.
set(LIBRARY_FILES
"""
    )
    for filename in sorted(library_files):
        fp.write(filename + "\n")
    fp.write(
        """\
)
"""
    )

with open(f"{PYRO_DIR}/cpython_library_files.cmake", "w") as fp:
    fp.write(
        f"""\
# This file was generated by `util/{SCRIPT_NAME}`.
#
# This is a list of the standard library files from `third-party/cpython/Lib`.
set(CPYTHON_LIBRARY_FILES
"""
    )
    for filename in sorted(cpython_library_files):
        fp.write(filename + "\n")
    fp.write(
        """\
)
"""
    )
