#!/bin/sh
rm -f library_files.txt
cat > library_files.txt << '__EOM__'
# This file was generated by `util/update_library_files.sh`.
__EOM__
find library \
    -type f \
    -name "*.py" \
    -printf '%P\n' \
    | LC_ALL=C sort \
    >> library_files.txt

rm -f library_cpython_files.txt
cat > library_cpython_files.txt << '__EOM__'
# This file was generated by `util/update_library_files.sh`.
#
# This is a list of the standard library files from `third-party/cpython/Lib`.
__EOM__
find third-party/cpython/Lib \
    -name "__pycache__" -prune -o \
    -type f \
    -printf '%P\n' \
    | grep -x --invert-match --fixed-strings --file=library_files.txt \
    | LC_ALL=C sort \
    >> library_cpython_files.txt
